import 'package:flutter/material.dart';
import 'package:flutterapp/ddfdfdapp/generatedprofilewidget/generated/GeneratedFrame12Widget.dart';
import 'package:flutterapp/ddfdfdapp/generatedprofilewidget/generated/GeneratedFrame11Widget.dart';
import 'package:flutterapp/ddfdfdapp/generatedprofilewidget/generated/GeneratedFrame13Widget.dart';
import 'package:flutterapp/ddfdfdapp/generatedprofilewidget/generated/GeneratedFrame8Widget.dart';

/* Frame profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(76, 0, 0, 0),
            offset: Offset(10.0, 10.0),
            blurRadius: 40.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(30.0),
        child: Container(
          width: 414.0,
          height: 896.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(30.0),
            border: Border.all(
              width: 5.0,
              color: Color.fromARGB(255, 0, 0, 0),
            ),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(30.0),
                  child: Container(
                    color: Color.fromARGB(255, 129, 13, 13),
                  ),
                ),
                Positioned(
                  left: 14.0,
                  top: 42.0,
                  right: null,
                  bottom: null,
                  width: 386.0,
                  height: 250.0,
                  child: GeneratedFrame8Widget(),
                ),
                Positioned(
                  left: 18.0,
                  top: 341.0,
                  right: null,
                  bottom: null,
                  width: 158.0,
                  height: 183.0,
                  child: GeneratedFrame11Widget(),
                ),
                Positioned(
                  left: 238.0,
                  top: 341.0,
                  right: null,
                  bottom: null,
                  width: 158.0,
                  height: 183.0,
                  child: GeneratedFrame12Widget(),
                ),
                Positioned(
                  left: 128.0,
                  top: 634.0,
                  right: null,
                  bottom: null,
                  width: 158.0,
                  height: 183.0,
                  child: GeneratedFrame13Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
